spring:
  datasource:
    url: jdbc:h2:file:${HOME}/gridcapa/task-manager
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: ${GRIDCAPA_RABBITMQ_HOST:localhost}
    port: ${GRIDCAPA_RABBITMQ_PORT:5672}
    username: ${GRIDCAPA_RABBITMQ_USERNAME:gridcapa}
    password: ${GRIDCAPA_RABBITMQ_PASSWORD:gridcapa}
  cloud:
    stream:
      default:
        group: task-manager
      bindings:
        handleMinioEvent-in-0:
          destination: gridcapa.minio.events
        handleTaskStatusUpdate-in-0:
          destination: task-status-updated
        handleTaskLogEventUpdate-in-0:
          destination: task-manager-logs-exchange
        task-updated:
          destination: task-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
        bindings:
          handleMinioEvent-in-0:
            consumer:
              exchange-type: fanout
    function:
      definition: handleMinioEvent;handleTaskStatusUpdate;handleTaskLogEventUpdate

task-server:
  minio:
    connect:
      url: ${GRIDCAPA_MINIO_URL:http://localhost:9000}
      access-key: ${GRIDCAPA_MINIO_ACCESS_KEY:gridcapa}
      secret-key: ${GRIDCAPA_MINIO_SECRET_KEY:gridcapa}
  process:
    tag: CSE_D2CC
    timezone: CET
    inputs:
      - CGM