spring:
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  jpa:
    properties:
      order_insert: true
      order_updates: true
      jdbc:
        batch_size: 50
      hibernate:
        timezone:
          default_storage: NORMALIZE_UTC
    hibernate:
      ddl-auto: validate
  cloud:
    function:
      definition: consumeMinioEvent;consumeTaskStatusUpdate;consumeTaskEventUpdate
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

task-server:
  process:
    timezone: CET

purge-task-events:
  cron: 0 0 12 * * *
  nb-days: 7

stomp:
  heartbeat-client: 0
  heartbeat-server: 25000
  starting-ws-endpoint: /ws/tasks/notify
  notify: /task
  receive-request: /app
